=== Alex-Linhares/lida-framework/configs/LidaXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://ccrg.cs.memphis.edu/LidaXMLSchema" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ccrg.cs.memphis.edu/LidaXMLSchema">


    <complexType name="module">
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="submodules" type="tns:modules"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
            <element name="associatedmodule" type="tns:associatedmodule" maxOccurs="unbounded" minOccurs="0"></element>
            <element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="isdriver" type="boolean" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="initializerclass" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>





    <complexType name="modules">
    	<sequence>
    		<element name="module" type="tns:module" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    
    <complexType name="drivers">
    	<sequence>
    		<element name="driver" type="tns:driver" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="driver">
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="associatedmodule" type="tns:associatedmodule"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="ticksperstep" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="initializerclass" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <element name="lida" type="tns:lida"></element>
    
    <complexType name="lida">
    	<sequence>
            <element name="taskmanager" type="tns:taskmanager" maxOccurs="1" minOccurs="1"></element>
            <element name="submodules" type="tns:modules" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="drivers" type="tns:drivers" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="listeners" type="tns:listeners" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="param">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="string" use="required"></attribute>
    			<attribute name="type" use="optional">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="int"></enumeration>
    						<enumeration value="double"></enumeration>
    						<enumeration value="string"></enumeration>
    						<enumeration value="boolean"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="listener">
    	<sequence>
    		<element name="listenertype" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="modulename" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="listenername" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="listeners">
    	<sequence>
    		<element name="listener" type="tns:listener" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="taskmanager">
    	<sequence>
    		<element name="param" type="tns:param" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="associatedmodule">
       <simpleContent>
      <extension base="string">
    	<attribute name="function" type="string" use="optional"></attribute>
      </extension>
    </simpleContent>
    </complexType>
</schema>

=== Alex-Linhares/lida-framework/configs/lida.xml
<?xml version="1.0" encoding="UTF-8"?>
<lida xmlns="http://ccrg.cs.memphis.edu/LidaXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ccrg.cs.memphis.edu/LidaXMLSchema LidaXMLSchema.xsd ">
	<taskmanager>
		<param name="taskManager.tickDuration">1</param>
		<param name="taskManager.maxNumberOfThreads">100</param>
	</taskmanager>
	<submodules>
		<module name="Environment">
			<class>example.wumpus.environment.WumpusWorldEnvironment</class>
		     	<param name="height"> 10 </param>
				<param name="width">10 </param>
			<isdriver>true</isdriver>			
		</module>
		<module name="SensoryMemory">
			<class>example.wumpus.sensoryMemory.WumpusSensoryMemory</class>
			<associatedmodule>Environment</associatedmodule>
			<param name="sensoryMemory.ticksPerStep">12 </param>
		</module>
		<module name="SensoryMotorMemory">
			<class>edu.memphis.ccrg.lida.sensorymotormemory.SensoryMotorMemoryImpl</class>
		</module>
		<module name="PerceptualAssociativeMemory">
			<class>edu.memphis.ccrg.lida.pam.PerceptualAssociativeMemoryImpl</class>
			<param name="pam.ticksPerStep">8 </param>
			<param name="pam.Upscale" type="double">.7 </param>
			<param name="pam.Downscale" type="double">.6 </param>
			<param name="pam.Selectivity" type="double">.5 </param>
			<param name="pam.newNodeType" type="string">PamNodeImpl</param>
			<initializerclass>example.wumpus.pam.WumpusPamInitializer</initializerclass>
		</module>
		<module name="TransientEpisodicMemory">
			<class>edu.memphis.ccrg.lida.transientepisodicmemory.TemImpl</class>
		</module>
		<module name="DeclarativeMemory">
			<class>edu.memphis.ccrg.lida.transientepisodicmemory.TemImpl</class>
		</module>
		<module name="Workspace">
			<class>edu.memphis.ccrg.lida.workspace.main.WorkspaceImpl</class>
			<submodules>
				<module name="EpisodicBuffer">
					<class>edu.memphis.ccrg.lida.workspace.workspaceBuffer.WorkspaceBufferImpl</class>
				</module>
				<module name="PerceptualBuffer">
					<class>edu.memphis.ccrg.lida.workspace.workspaceBuffer.WorkspaceBufferImpl</class>
				</module>
				<module name="CurrentSituationalModel">
					<class>edu.memphis.ccrg.lida.workspace.workspaceBuffer.WorkspaceBufferImpl</class>
				</module>
				<module name="BroadcastQueue">
					<class>edu.memphis.ccrg.lida.workspace.broadcastbuffer.BroadcastQueueImpl</class>
					<param name="workspace.broadcastQueueCapacity">20 </param>
				</module>
			</submodules>
		</module>
		<module name="GlobalWorkspace">
			<class>edu.memphis.ccrg.lida.globalworkspace.GlobalWorkspaceImpl</class>
			<param name="globalWorkspace.delayNoBroadcast">100 </param>
			<param name="globalWorkspace.delayNoNewCoalition">50 </param>
			<param name="globalWorkspace.aggregateActivationThreshold">.8 </param>
			<param name="globalWorkspace.individualActivationThreshold">.5 </param>
			<isdriver>true</isdriver>
			<initializerclass>example.wumpus.initialization.GlobalWorkspaceInitializer</initializerclass>
		</module>
		<module name="ProceduralMemory">
			<class>edu.memphis.ccrg.lida.proceduralmemory.ProceduralMemoryImpl</class>
			<param name="proceduralMemory.ticksPerStep"> 14 </param>
			<initializerclass>example.wumpus.procedural.WumpusProceduralMemoryInitializer</initializerclass>
		</module>
		<module name="ActionSelection">
			<class>edu.memphis.ccrg.lida.actionselection.ActionSelectionImpl</class>
			<param name="actionSelection.ticksPerStep"> 10</param>
		</module>
	</submodules>
	<drivers>
		<driver name="SensoryMemoryDriver">
			<class>edu.memphis.ccrg.lida.sensorymemory.SensoryMemoryDriver</class>
			<associatedmodule>SensoryMemory</associatedmodule>
			<ticksperstep>5</ticksperstep>
		</driver>
		<driver name="PamDriver">
			<class>edu.memphis.ccrg.lida.pam.PamDriver</class>
			<associatedmodule>PerceptualAssociativeMemory</associatedmodule>
			<ticksperstep>10</ticksperstep>
		</driver>
		<driver name="AttentionDriver">
			<class>edu.memphis.ccrg.lida.attention.AttentionDriver</class>
			<associatedmodule>Workspace</associatedmodule>
			<associatedmodule>GlobalWorkspace</associatedmodule>
			<initializerclass>example.wumpus.initialization.AttentionCodeletInitializer</initializerclass>
			<ticksperstep>8</ticksperstep>
		</driver>
		<driver name="SbCodeletDriver">
			<class>edu.memphis.ccrg.lida.workspace.structurebuildingcodelets.SbCodeletDriver</class>
			<associatedmodule>Workspace</associatedmodule>
			<initializerclass>example.wumpus.initialization.SbCodeletInitializer</initializerclass>
			<ticksperstep>5</ticksperstep>
		</driver>
		<driver name="ProceduralDriver">
			<class>edu.memphis.ccrg.lida.proceduralmemory.ProceduralMemoryDriver</class>
			<associatedmodule>ProceduralMemory</associatedmodule>
			<ticksperstep>5</ticksperstep>
		</driver>
	</drivers>
	<listeners>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.pam.PamListener</listenertype>
			<modulename>PerceptualAssociativeMemory</modulename>
			<listenername>Workspace</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.transientepisodicmemory.CueListener</listenertype>
			<modulename>Workspace</modulename>
			<listenername>DeclarativeMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.transientepisodicmemory.CueListener</listenertype>
			<modulename>Workspace</modulename>
			<listenername>TransientEpisodicMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.globalworkspace.BroadcastListener</listenertype>
			<modulename>GlobalWorkspace</modulename>
			<listenername>PerceptualAssociativeMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.globalworkspace.BroadcastListener</listenertype>
			<modulename>GlobalWorkspace</modulename>
			<listenername>Workspace</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.globalworkspace.BroadcastListener</listenertype>
			<modulename>GlobalWorkspace</modulename>
			<listenername>TransientEpisodicMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.globalworkspace.BroadcastListener</listenertype>
			<modulename>GlobalWorkspace</modulename>
			<listenername>ProceduralMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.proceduralmemory.ProceduralMemoryListener</listenertype>
			<modulename>ProceduralMemory</modulename>
			<listenername>ActionSelection</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.actionselection.ActionSelectionListener</listenertype>
			<modulename>ActionSelection</modulename>
			<listenername>SensoryMotorMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.sensorymotormemory.SensoryMotorListener</listenertype>
			<modulename>SensoryMotorMemory</modulename>
			<listenername>Environment</listenername>
		</listener>
		
		<!-- Inter-module connections that are not currently used but are required by the LIDA model.  -->	
		<listener>
			<listenertype>edu.memphis.ccrg.lida.sensorymotormemory.SensoryMotorListener</listenertype>
			<modulename>SensoryMotorMemory</modulename>
			<listenername>SensoryMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.sensorymemory.SensoryMemoryListener</listenertype>
			<modulename>SensoryMemory</modulename>
			<listenername>SensoryMotorMemory</listenername>
		</listener>	
		<listener>
			<listenertype>edu.memphis.ccrg.lida.workspace.main.WorkspaceListener</listenertype>
			<modulename>Workspace</modulename>
			<listenername>PerceptualAssociativeMemory</listenername>
		</listener>
		<listener>
			<listenertype>edu.memphis.ccrg.lida.sensorymotormemory.SensoryMotorListener</listenertype>
			<modulename>SensoryMotorMemory</modulename>
			<listenername>Workspace</listenername>
		</listener>
	</listeners>
</lida>
